base_model: /workspace/models/DeepSeek-R1-Distill-Llama-70B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

#is_llama_derived_model: true
#load_in_8bit: true

datasets:
  - path: /workspace/data/train.jsonl
    type:
      system_prompt: ""
      field_system: system
      field_instruction: ""
      field_input: input
      field_output: output
      format: "{input}"

test_datasets:
  - path: /workspace/data/test.jsonl
    ds_type: json
    # You need to specify a split. For "json" datasets the default split is called "train".
    split: train
    type:
      system_prompt: ""
      field_system: system
      field_instruction: ""
      field_input: input
      field_output: output
      format: "{input}"

dataset_prepared_path: /workspace/dataset_prepared

output_dir: /workspace/finetuned_model
save_safetensors: true


default_system_message: ""

# Training parameters
sequence_len: 8192
adapter: lora
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj
micro_batch_size: 8
gradient_accumulation_steps: 8
num_epochs: 4 #1000
learning_rate: 1e-3 #1e-7
optimizer: adamw_bnb_8bit #adamw_torch
lr_scheduler: cosine

wandb_mode: "offline"
wandb_project: "cjeu-ali"
wandb_name: "cjeu-ali"
wandb_run_id: "cjeu-ali-1"
wandb_log_model: "checkpoint"

deepspeed: deepspeed_configs/zero1.json
#deepspeed: deepspeed_configs/zero3.json