base_model: ./models/DeepSeek-R1-Distill-Llama-8B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

datasets:
  - path: ./data/train_enriched.jsonl
    type: alpaca_chat.load_qa

val_set_size: 0.05
evals_per_epoch: 4
saves_per_epoch: 1

dataset_prepared_path: ./dataset_prepared

output_dir: ./finetuned_models
save_safetensors: true

default_system_message: ""

bf16:
fp16:
tf32: false

sequence_len: 8192
adapter: lora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.02
load_in_8bit: false
load_in_4bit: true
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

micro_batch_size: 1
gradient_checkpointing: 1

gradient_accumulation_steps: 8
num_epochs: 4 #1000
learning_rate: 1e-3 #1e-7
optimizer: adamw_8bit
lr_scheduler: cosine

wandb_mode: "online"
wandb_project: "cjeu-ali"
wandb_name: "cjeu-ali"
wandb_run_id: "cjeu-ali-1"
wandb_log_model: "checkpoint"

deepspeed: ./zero3.json
